[tool.poetry]
name = "repl_python3_TicTacToe"
version = "0.1.0"
description = ""
authors = ["FrerikNagel <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
jsons = "^1.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
